export const CONST_TOGGLE_SIDEBAR = "CONFIG_TOGGLE_SIDEBAR_EVENT";
export const CONST_TOGGLE_PROFILE = "CONFIG_TOGGLE_PROFILE_EVENT";
export const CONST_TOGGLE_NOTIFICATIONS = "CONFIG_TOGGLE_NOTIFICATIONS_EVENT";
export const CONST_TOGGLE_TOOLKIT = "CONFIG_TOGGLE_TOOLKIT_EVENT";
